### PR TITLE
Agenda

### PR DESCRIPTION
**Pull request by pritchardn**

### CODE REVIEW

**Comment by Tommoa** [comment]
Can we please make new branches for each week and then delete them? We have a mess of old meetings now.

**Comment by gozzarda** [comment]
We don't necessarily know when each meeting will be when we make the
agenda. What is the mess? Process logically should be to rename the file
once the meeting has happened, merge the agenda branch in, and make a new
agenda branch, surely?

**Comment by Tommoa** [comment]
The point is that we haven't merged for a few months, and now we have this huge PR that does multiple meetings, one of which hasn't actually happened and therefore cannot be merged. I think we should get in the habit of creating a new PR after every meeting and merging the old one once the minutes are confirmed, and it might be easier to do so with additional branches that then get deleted.

For the meantime, I'm going to cherry pick old meetings into the master branch to remove them from the PR so its only the last two meetings.

**Comment by Tommoa** [comment]
Ok, this PR is now ready to squash and merge at the next meeting. I'll open a new PR.

**Pull request closed without merging**
